name: piranha
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.79
  - coreutils=8.31
  - gofasta=0.0.6
  - mafft=7.490
  - medaka=1.0.3
  - minimap2=2.23
  - pip=21.3.1
  - python=3.6
  - racon=1.4.20
  - snakemake-minimal=6.8.0
pip:
  - git+https://github.com/ahstram/cigar.git