name: piranha
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.74
  - minimap2>=2.16
  - pip=19.3.1
  - python>=3.7
  - snakemake-minimal<=6.8.0
  - pip:
    - PyQt5==5.15
    - pyinstaller==4.7
    