name: piranha
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - coreutils=9.1
  - mafft
  - minimap2=2.17
  - samtools=1.11
  - bcftools=1.11
  - tabix=1.11
  - snakemake-minimal
  - iqtree>=2.2
  - mafft=7.508
  - jclusterfunk=0.0.25
