name: piranha
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python<3.10
  - zlib
  - gofasta
  - mafft
  - minimap2=2.11
  - samtools=1.11
  - bcftools=1.11
  - tabix=1.11
  - snakemake-minimal

