name: piranha
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - coreutils=8.31
  - gofasta=0.0.6
  - mafft=7.490
  - medaka
  - pysamstats
  - minimap2
  - racon=1.5
  - snakemake-minimal=6.8.0
