name: piranha
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - coreutils=8.31
  - biopython=1.79
  - minimap2=2.23
  - pip=21.3.1
  - python=3.6
  - snakemake-minimal=6.8.0
  - medaka=1.0.3
  - racon=1.4.20
    